
ax_isp_iq_param_t g_selected_params[] = {
    {AX_ISP_PARAM_VERSION, &ax_isp_version_param_sdr},
    {AX_ISP_PARAM_DEPURPLE, &depurple_param_sdr},
    {AX_ISP_PARAM_BLC, &blc_param_sdr},
    {AX_ISP_PARAM_GAMMA, &gamma_param_sdr},
    {AX_ISP_PARAM_DEMOSAIC, &demosaic_param_sdr},
    {AX_ISP_PARAM_GIC, &gic_param_sdr},
    {AX_ISP_PARAM_CSC, &csc_param_sdr},
    {AX_ISP_PARAM_CC, &cc_param_sdr},
    {AX_ISP_PARAM_SHARPEN, &sharpen_param_sdr},
    {AX_ISP_PARAM_MDE, &mde_param_sdr},
    {AX_ISP_PARAM_YNR, &ynr_param_sdr},
    {AX_ISP_PARAM_AYNR, &aynr_param_sdr},
    {AX_ISP_PARAM_CNR, &cnr_param_sdr},
    {AX_ISP_PARAM_ACNR, &acnr_param_sdr},
    {AX_ISP_PARAM_SCM, &scm_param_sdr},
    {AX_ISP_PARAM_YCPROC, &ycproc_param_sdr},
    {AX_ISP_PARAM_CCMP, &ccmp_param_sdr},
    {AX_ISP_PARAM_YCRT, &ycrt_param_sdr},
    {AX_ISP_PARAM_AINR, &ainr_param_sdr},
    {AX_ISP_PARAM_AICE, &aice_param_sdr},
    {AX_ISP_PARAM_AWB, &awb_param_sdr},
    {AX_ISP_PARAM_RLTM, &rltm_param_sdr},
    {AX_ISP_PARAM_RAW3DNR, &raw3dnr_param_sdr},
    {AX_ISP_PARAM_LSC, &lsc_param_sdr},
    {AX_ISP_PARAM_DPC, &dpc_param_sdr},
    {AX_ISP_PARAM_CA, &ca_param_sdr},
    {AX_ISP_PARAM_AE, &ae_param_sdr},
    {AX_ISP_PARAM_3DLUT, &isp_3dlut_param_sdr},
    {AX_ISP_PARAM_SCENE, &scene_param_sdr},
    {AX_ISP_PARAM_NONE, AX_NULL},
};
